.TH "Racional.h" 3 "Jueves, 27 de Septiembre de 2018" "ClaseRacional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Racional.h \- Fichero cabecera del TDA \fBRacional\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBRacional\fP"
.br
.RI "\fIT\&.D\&.A\&. \fBRacional\fP\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Fichero cabecera del TDA \fBRacional\fP\&. 


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ClaseRacional del código fuente\&.
