.TH "repConjunto" 3 "Jueves, 27 de Septiembre de 2018" "ClaseRacional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repConjunto \- Rep del TDA \fBRacional\fP 

.SH "Invariante de la representación"
.PP
El invariante es \fIrep\&.den!=0\fP 
.SH "Función de abstracción"
.PP
Un objeto válido \fIrep\fP del TDA \fBRacional\fP representa al valor
.PP
(rep\&.num,rep\&.den) 
