#!/bin/bash
#Grupo Prácticas: AC-2
#Descripción: Ejecuta la Suma de Vectores en C desde 16384 hasta 67108864
#Uso: ./script_pc.sh

#DEFINICION DE MINIMO Y MAXIMO DE CALCULO
MIN=16384
MAX=67108864

#CONSTRUCCION DE NOMBRES DE ARCHIVO EJECUTABLES
TARGET="SumaVectoresC"
OMP_PARALLEL="PARALLEL_"
OMP_FOR="FOR_"
OMP_SECTIONS="SECTIONS_"
SECUENCIAL="SECUENCIAL_"

FILENO1=$OMP_PARALLEL$OMP_FOR$TARGET
FILENO2=$OMP_PARALLEL$OMP_SECTIONS$TARGET
FILENO3=$SECUENCIAL$TARGET

DIRECTORY="."

#CONSTRUCCION DE ARCHIVOS DE VOLCADO DE SALIDA

OUT_TARGET="TIEMPOS_"
OUT_PC="PC"
OUT_EXT=".txt"

OUT_FILENO1=$OUT_TARGET$OMP_FOR$OUT_PC$OUT_EXT
OUT_FILENO2=$OUT_TARGET$OMP_SECTIONS$OUT_PC$OUT_EXT
OUT_FILENO3=$OUT_TARGET$SECUENCIAL$OUT_PC$OUT_EXT

OUT_DIRECTORY="tiempos"

#BORRADO DE ARCHIVOS POR SI EXISTIAN PREVIAMENTE
rm -r $OUT_DIRECTORY 2> /dev/null

#COMPILACION DE OBJETOS
echo -e " >>> COMPILANDO OBJETOS <<< "
make 2> /dev/null

#EJECUCION DE SCRIPT: TIEMPOS SECUENCIAL

mkdir -p $OUT_DIRECTORY

echo -e "\n>>> EJECUCION DE PROGRAMA CON OMP PARALLEL [SECUENCIAL] <<<"
for((N=$MIN; N<=$MAX; N=N*2))
do
	echo " --> OBTENIENDO TIEMPO PARA DIMENSION [$N] DE [$MAX]"
	./$DIRECTORY/$FILENO3 $N >> $OUT_DIRECTORY/$OUT_FILENO3
	echo " " >> $OUT_DIRECTORY/$OUT_FILENO3
done

#DEFINICION DE HEBRAS A EJECUTAR EN PC
NUM_HEBRAS=4
set omp_num_threads $NUM_HEBRAS

#EJECUCION DE SCRIPT: TIEMPOS FOR

mkdir -p $OUT_DIRECTORY

echo -e "\n>>> EJECUCION DE PROGRAMA CON OMP PARALLEL [FOR] <<<"
echo -e "NUM HEBRAS DE EJECUCION: $NUM_HEBRAS\n" >> $OUT_DIRECTORY/$OUT_FILENO1
for((N=$MIN; N<=$MAX; N=N*2))
do
	echo " --> OBTENIENDO TIEMPO PARA DIMENSION [$N] DE [$MAX]"
	./$DIRECTORY/$FILENO1 $N >> $OUT_DIRECTORY/$OUT_FILENO1
	echo " " >> $OUT_DIRECTORY/$OUT_FILENO1
done

#EJECUCION DE SCRIPT: TIEMPOS SECTIONS

mkdir -p $OUT_DIRECTORY

echo -e "\n>>> EJECUCION DE PROGRAMA CON OMP PARALLEL [SECTIONS] <<<"
echo -e "NUM HEBRAS DE EJECUCION: $NUM_HEBRAS\n" >> $OUT_DIRECTORY/$OUT_FILENO2
for((N=$MIN; N<=$MAX; N=N*2))
do
	echo " --> OBTENIENDO TIEMPO PARA DIMENSION [$N] DE [$MAX]"
	./$DIRECTORY/$FILENO2 $N >> $OUT_DIRECTORY/$OUT_FILENO2
	echo " " >> $OUT_DIRECTORY/$OUT_FILENO2
done

#ELIMINACION DE CODIGOS EJECUTABLES
echo -e "\n >>> ELIMINANDO OBJETOS <<< "
make clean 2> /dev/null

