SELECT DISTINCT CODPRO FROM VENTAS V1 WHERE NOT EXISTS(
    (SELECT DISTINCT CIUDAD FROM PROYECTO WHERE CODPJ IN(
    	SELECT DISTINCT CODPJ FROM VENTAS WHERE CODPJ='S3'))
    MINUS
   (SELECT DISTINCT CIUDAD FROM PROYECTO WHERE CODPJ IN(
   	SELECT DISTINCT CODPJ FROM VENTAS WHERE VENTAS.CODPJ=V1.CODPJ))) 
   AND CODPRO!='S3';

